### ISSUE TITLE
No integration of pre-trained word2vec model

### ISSUE THREAD

**Issue by CoderSherlock** [Yugnaynehc/chatbot#1]
~~~~bash
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
.
2018-04-14 20:56:28,218 : INFO : loading Word2Vec object from model/word2vec_gensim
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from Seq2Seq import chat
  File "/home/pengzhan/Github/chatbot/Seq2Seq.py", line 35, in <module>
    model = gensim.models.Word2Vec.load(os.path.join("model", "word2vec_gensim"))
  File "/home/pengzhan/.local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 975, in load
    return super(Word2Vec, cls).load(*args, **kwargs)
  File "/home/pengzhan/.local/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 629, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/home/pengzhan/.local/lib/python2.7/site-packages/gensim/models/base_any2vec.py", line 278, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/home/pengzhan/.local/lib/python2.7/site-packages/gensim/utils.py", line 425, in load
    obj = unpickle(fname)
  File "/home/pengzhan/.local/lib/python2.7/site-packages/gensim/utils.py", line 1329, in unpickle
    with smart_open(fname, 'rb') as f:
  File "/home/pengzhan/.local/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 176, in smart_open
    return file_smart_open(parsed_uri.uri_path, mode, encoding=encoding, errors=errors)
  File "/home/pengzhan/.local/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 671, in file_smart_open
    raw_fobj = open(fname, raw_mode)
IOError: [Errno 2] No such file or directory: 'model/word2vec_gensim'
~~~~

Could you share download script in the repo?

**Comment by Yugnaynehc** [comment]
Just come back to Beijing and take a copy of that. :grinning:
